### ISSUE TITLE
Consider HTTPS instead of only HTTP

### ISSUE THREAD

**Issue by grdryn** [fedora-infra/planet#10]
As mentioned in [this discussion on discourse](https://discussion.fedoraproject.org/t/one-fedora-website-does-not-support-https/42745), Fedora Planet currently doesn't support HTTPS at all.

This migration effort would seem like a good time to consider addressing that. [Kevin points out](https://discussion.fedoraproject.org/t/one-fedora-website-does-not-support-https/42745/4) that all of the aggregated feeds would need to support HTTPS to do that. If the ini files here are going to be the source of truth rather than the per-user files in fedora people home directories, then it should be fairly straightforward to do it here I think.

**Comment by phsmoura** [comment]
Yep, it was solved deploying it on OCP. New planet is still running [here](https://planet.apps.ocp.fedoraproject.org/) and we are about to retire the old one just need to change the script that retrieves the information because we changed the attributes to multi-valued, but its using HTTPS now
