### ISSUE TITLE
Most feeds are missing from the ini files

### ISSUE THREAD

**Issue by grdryn** [fedora-infra/planet#11]
The live Fedora Planet instance claims that there are 806 feeds: http://fedoraplanet.org/heads.html, whereas there are only a handful in people.ini.

**Comment by nirik** [comment]
FYI, the current planet setup runs on fedorapeople.org, it just looks for a ".planet" file in every users homedirectory. 

Ideally however, we would use the new account systems "Website or Blog URL" field via fasjson. 

We may also be able to change the account system so it requires https...

**Comment by phsmoura** [comment]
We still didnt retire the old planet thats why its showing +800 feeds there, but new planet also had missing feeds because it only allows HTTPS, that was fixed enforcing HTTPS in noggin and that PR was merged this week, so Im closing this issue.
