### ISSUE TITLE
Consider a separate container for feed generation

### ISSUE THREAD

**Issue by grdryn** [fedora-infra/planet#9]
Currently, we build a container image with the feeds generated as part of that build. While this is fine for initial development, it would not be optimal to build a new image every \<interval> to update the feeds.

Instead, I'd like to propose that there are two containers, with shared storage:
- The main container will be the static site, served by httpd as it is now
- The secondary container will run periodically, running `build-planets.sh` (or something similar) to update the feeds in the shared storage, which will then be picked up automatically by the httpd container.

Depending on the storage options on the cluster where this will run, this could either be done as a single pod with two containers, or something more elaborate like a long-running httpd pod, with a cronjob pod that Kubernetes runs every \<interval>.

**Comment by phsmoura** [comment]
Yep, that was also done. Its now a python script, but it runs in secondary container triggered by cron and it updates a shared storage
